// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8ikmw2ZcfHAOHD5Vntn7SzLjf2d2HqJI',
    appId: '1:609363151626:web:8b276759a3b9cac7c948f3',
    messagingSenderId: '609363151626',
    projectId: 'connectcall-9fca5',
    authDomain: 'connectcall-9fca5.firebaseapp.com',
    storageBucket: 'connectcall-9fca5.firebasestorage.app',
    measurementId: 'G-ZPZ4JF5SL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApFkUQ92624hQWTynU-_oPhbgnwpgwpIs',
    appId: '1:609363151626:android:ffd1a27d2345de09c948f3',
    messagingSenderId: '609363151626',
    projectId: 'connectcall-9fca5',
    storageBucket: 'connectcall-9fca5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDCvndlu-cUvL6W6RUMxX-xOYHQXgHvXI',
    appId: '1:609363151626:ios:11597cfdcafd2ce9c948f3',
    messagingSenderId: '609363151626',
    projectId: 'connectcall-9fca5',
    storageBucket: 'connectcall-9fca5.firebasestorage.app',
    iosBundleId: 'com.example.connectCall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDCvndlu-cUvL6W6RUMxX-xOYHQXgHvXI',
    appId: '1:609363151626:ios:11597cfdcafd2ce9c948f3',
    messagingSenderId: '609363151626',
    projectId: 'connectcall-9fca5',
    storageBucket: 'connectcall-9fca5.firebasestorage.app',
    iosBundleId: 'com.example.connectCall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8ikmw2ZcfHAOHD5Vntn7SzLjf2d2HqJI',
    appId: '1:609363151626:web:209402d03d3c962ec948f3',
    messagingSenderId: '609363151626',
    projectId: 'connectcall-9fca5',
    authDomain: 'connectcall-9fca5.firebaseapp.com',
    storageBucket: 'connectcall-9fca5.firebasestorage.app',
    measurementId: 'G-DJZK93TSE6',
  );
}
